version: '3.3'

services:
  db:
    container_name: db
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  backend:
    container_name: back
    image: ilyakhakhalkin/foodgram_backend:latest
    restart: always
    command: >
      bash -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput"
    volumes:
      - static_value:/back/static/
      - media_value:/back/media/
    depends_on:
      - db
    env_file:
      - ../.env

  frontend:
    container_name: front
    image: ilyakhakhalkin/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    container_name: nginx
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    restart: always
    depends_on:
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:
