# Generated by Django 3.2.16 on 2023-02-01 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_first_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='Нельзя подписаться дважды',
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='Нельзя подписаться на себя',
        ),
    ]
