# Generated by Django 3.2.16 on 2023-02-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230201_1447'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='Нельзя подписаться дважды'),
        ),
    ]
