# Generated by Django 3.2.16 on 2023-02-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_group'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='Нельзя подписаться дважды',
        ),
    ]
